### PR TITLE
PLAT-870 Failed with KeyError (update version for laravel-zerorpc)

### PR DESCRIPTION
**Pull request by BarryPaneer**
## Summary of changes

the version of zerorpc should be higher than 1.2.5

## How to Test
1) cd laravel-zerorpc
2) composer install

/fyi: @mark-juwai , @zhangjustin : Please review.

### CODE REVIEW

**Review by mark-juwai — APPROVED** [review]
Not sure if we have to do this, but it works.

**Review by zhangjustin — APPROVED** [review]

**Comment by BarryPaneer** [comment]
please, merge, thx.

**Comment by mark-juwai** [comment]
Merged and released `1.0.4`.

**Comment by BarryPaneer** [comment]
okey

**Pull request merged**
